/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author bruno
 */
public class TelaResultado extends javax.swing.JFrame {

    /**
     * Creates new form Resultado
     */
    public TelaResultado() {
        initComponents();
    }

    public void setValorIRLabel(String resultado) {
        valorIRLabel.setText(resultado);
    }

    public void setBaseCalculoLabel(String resultado) {
        BaseCalcLabel.setText(resultado);
    }

    public void setValorPrevLabel(String resultado) {
        valorPrevLabel.setText(resultado);
    }
    
    public void setSalarioLiquido(String resultado){
        SalarioLiquido.setText(resultado);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valorIRLabel = new javax.swing.JLabel();
        valorPrevLabel = new javax.swing.JLabel();
        BaseCalcLabel = new javax.swing.JLabel();
        SalarioLiquido = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Resultado");
        setMaximumSize(new java.awt.Dimension(700, 330));
        setMinimumSize(new java.awt.Dimension(700, 330));
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().setLayout(null);

        valorIRLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        valorIRLabel.setForeground(new java.awt.Color(255, 0, 0));
        valorIRLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorIRLabel.setText("TESTE");
        valorIRLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(valorIRLabel);
        valorIRLabel.setBounds(70, 20, 570, 62);

        valorPrevLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        valorPrevLabel.setForeground(new java.awt.Color(255, 51, 0));
        valorPrevLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valorPrevLabel.setText("TESTE");
        valorPrevLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        getContentPane().add(valorPrevLabel);
        valorPrevLabel.setBounds(70, 100, 570, 50);

        BaseCalcLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BaseCalcLabel.setForeground(new java.awt.Color(255, 0, 0));
        BaseCalcLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        BaseCalcLabel.setText("TESTE");
        BaseCalcLabel.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        getContentPane().add(BaseCalcLabel);
        BaseCalcLabel.setBounds(70, 160, 570, 50);

        SalarioLiquido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        SalarioLiquido.setForeground(new java.awt.Color(0, 153, 0));
        SalarioLiquido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalarioLiquido.setText("TESTE");
        SalarioLiquido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        getContentPane().add(SalarioLiquido);
        SalarioLiquido.setBounds(70, 220, 570, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo0.jpg"))); // NOI18N
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 710, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        this.dispose();
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaResultado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaResultado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BaseCalcLabel;
    private javax.swing.JLabel SalarioLiquido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel valorIRLabel;
    private javax.swing.JLabel valorPrevLabel;
    // End of variables declaration//GEN-END:variables
}
