/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import view.TelaPrincipal;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/**
 *
 * @author bruno
 */
public class TelaHoraExtra extends javax.swing.JFrame {

    /**
     * Creates new form TelaHoraExtra
     */
    private TelaPrincipal tp;
    
    public TelaHoraExtra(TelaPrincipal tp){
        
        initComponents();
        
        
        BtnCalcularHext.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                double vencimento = Double.parseDouble(vencimentoText.getText().replace(",", "."));
                double chMensal = Double.parseDouble(chMensalText.getText().replace(",", "."));
                double numHexText = Double.parseDouble(numHextText.getText().replace(",", "."));
                double valorHora, valorHoraExtra;
                valorHora = vencimento / chMensal;
                valorHoraExtra = ((valorHora * 0.5) + valorHora) * numHexText;
                //resultLabel.setText("oii");
                tp.inserirValorHoraExtra(String.format("%.2f", valorHoraExtra).replace(",", "."));
                
            }
           
           
        });
    }
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vencimentoText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        chMensalText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        numHextText = new javax.swing.JTextField();
        BtnCalcularHext = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hora Extra");
        setMinimumSize(new java.awt.Dimension(280, 340));
        setPreferredSize(new java.awt.Dimension(280, 340));
        getContentPane().setLayout(null);

        vencimentoText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vencimentoText.setText("0");
        vencimentoText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vencimentoTextFocusGained(evt);
            }
        });
        getContentPane().add(vencimentoText);
        vencimentoText.setBounds(10, 30, 155, 41);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Digite o vencimento");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 144, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Digite a Carga Horaria Mensal:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 84, 180, 16);

        chMensalText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        chMensalText.setText("0");
        chMensalText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chMensalTextFocusGained(evt);
            }
        });
        getContentPane().add(chMensalText);
        chMensalText.setBounds(10, 100, 155, 41);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Digite o número de horas extras trabalhadas:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 150, 260, 16);

        numHextText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        numHextText.setText("0");
        numHextText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                numHextTextFocusGained(evt);
            }
        });
        numHextText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                numHextTextKeyPressed(evt);
            }
        });
        getContentPane().add(numHextText);
        numHextText.setBounds(10, 170, 155, 41);

        BtnCalcularHext.setText("Calcular valor das Horas");
        BtnCalcularHext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularHextActionPerformed(evt);
            }
        });
        getContentPane().add(BtnCalcularHext);
        BtnCalcularHext.setBounds(10, 240, 160, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundo0.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setMaximumSize(new java.awt.Dimension(1242, 350));
        jLabel4.setMinimumSize(new java.awt.Dimension(1242, 350));
        jLabel4.setPreferredSize(new java.awt.Dimension(1242, 350));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 280, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void fecharJanela(){
        this.dispose();
    }
    private void BtnCalcularHextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularHextActionPerformed
        
    }//GEN-LAST:event_BtnCalcularHextActionPerformed

    private void vencimentoTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vencimentoTextFocusGained
        vencimentoText.setText("");
    }//GEN-LAST:event_vencimentoTextFocusGained

    private void chMensalTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chMensalTextFocusGained
        chMensalText.setText("");
    }//GEN-LAST:event_chMensalTextFocusGained

    private void numHextTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_numHextTextFocusGained
        numHextText.setText("");
    }//GEN-LAST:event_numHextTextFocusGained

    private void numHextTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numHextTextKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_numHextTextKeyPressed

    /**
     * @param args the command line arguments
     */
   
    /*
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaHoraExtra().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcularHext;
    private javax.swing.JTextField chMensalText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField numHextText;
    private javax.swing.JTextField vencimentoText;
    // End of variables declaration//GEN-END:variables
}
