/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import javax.swing.JOptionPane;
import view.TelaPrincipal;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
/**
 *
 * @author BPA
 */
public class TelaAdicionalNoturno extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdicionalNoturno
     */
    private TelaPrincipal tp;
    
    public TelaAdicionalNoturno(TelaPrincipal tp) {
        initComponents();
        
        
        btnCalcular.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e){
                double hnoturna = Double.parseDouble(hnoturnasText.getText().replace(",", "."));
                double chmensal = Double.parseDouble(chMensalText.getText().replace(",", "."));;
                
                double vencimento=0,valorHora=0,ValorTotal;
                vencimento=Double.parseDouble(vencimentoText.getText().replace(",", "."));
                
                valorHora = (vencimento/chmensal)*0.2857; //1,7142
                
                ValorTotal = valorHora*(hnoturna*1.1429);
                tp.inserirValorAdicionalNoturno(String.format("%.2f",ValorTotal));
                
                //ResultLabel.setText(String.format("%.2f",ValorTotal));
                
                
            }
           
           
        });
        
    }

    private TelaAdicionalNoturno() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        hnoturnasText = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        vencimentoText = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        chMensalText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(300, 340));
        setPreferredSize(new java.awt.Dimension(330, 374));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Digite a quantidade de horas noturnas: (22:00 às 05:00)");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 180, 272, 14);

        hnoturnasText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hnoturnasTextActionPerformed(evt);
            }
        });
        getContentPane().add(hnoturnasText);
        hnoturnasText.setBounds(40, 200, 109, 33);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular);
        btnCalcular.setBounds(40, 260, 71, 23);

        jLabel2.setText("Digite o vencimento:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 40, 98, 14);
        getContentPane().add(vencimentoText);
        vencimentoText.setBounds(40, 60, 108, 29);

        jLabel3.setText("Digite a carga horária mensal:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(40, 100, 143, 14);
        getContentPane().add(chMensalText);
        chMensalText.setBounds(40, 130, 106, 35);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hnoturnasTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hnoturnasTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hnoturnasTextActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionalNoturno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionalNoturno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionalNoturno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdicionalNoturno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdicionalNoturno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JTextField chMensalText;
    private javax.swing.JTextField hnoturnasText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField vencimentoText;
    // End of variables declaration//GEN-END:variables
}
